/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	rbacv1alpha1 "github.com/ruiwang47/k8s-istio-client/pkg/apis/rbac/v1alpha1"
	versioned "github.com/ruiwang47/k8s-istio-client/pkg/client/clientset/versioned"
	internalinterfaces "github.com/ruiwang47/k8s-istio-client/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/ruiwang47/k8s-istio-client/pkg/client/listers/rbac/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterRbacConfigInformer provides access to a shared informer and lister for
// ClusterRbacConfigs.
type ClusterRbacConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ClusterRbacConfigLister
}

type clusterRbacConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewClusterRbacConfigInformer constructs a new informer for ClusterRbacConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterRbacConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterRbacConfigInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredClusterRbacConfigInformer constructs a new informer for ClusterRbacConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterRbacConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RbacV1alpha1().ClusterRbacConfigs(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RbacV1alpha1().ClusterRbacConfigs(namespace).Watch(options)
			},
		},
		&rbacv1alpha1.ClusterRbacConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterRbacConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterRbacConfigInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterRbacConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&rbacv1alpha1.ClusterRbacConfig{}, f.defaultInformer)
}

func (f *clusterRbacConfigInformer) Lister() v1alpha1.ClusterRbacConfigLister {
	return v1alpha1.NewClusterRbacConfigLister(f.Informer().GetIndexer())
}
